spring:
  application:
    name: Home Service System
  servlet:
    multipart:
      enabled: true
      max-file-size: 300KB
      max-request-size: 300KB
  mail:
    host: smtp.gmail.com
    port: 587
    username: freshomeee@gmail.com
    password: lmizxganzhjjmine
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_schema: home_security
  security:
    user:
      name: admin
      password: admin
#        format_sql: true

server:
  port: 8081



#logging:
#  level:
#    org:
#      hibernate:
#        SQL : debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder : TRACE


