spring:
  application:
    name: Home Service System
  servlet:
    multipart:
      enabled: true
      max-file-size: 300KB
      max-request-size: 300KB

  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        default_schema: home
  security:
    user:
      name: admin
      password: admin
#        format_sql: true

server:
  port: 8081

#logging:
#  level:
#    org:
#      hibernate:
#        SQL : debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder : TRACE


